version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: "blog"
    environment:
      NITRO_PORT: 3001
    ports:
      - 3001:3001
    command: [ "node", "./server/index.mjs" ]
    networks:
      - nuxt-networks

networks:
  nuxt-networks:
